[package]
name = "options-rs"
version = "0.1.0"
edition = "2021"
description = "Low-latency Alpaca Markets API client for options pricing and volatility surface calculations"
authors = ["Options Team"]

[dependencies]
# Alpaca Markets API client
apca = { version = "0.25.1" }

# Async runtime
tokio = { version = "1.28", features = ["full", "rt-multi-thread"] }

# Logging
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

# Configuration
dotenv = "0.15"
config = "0.13"

# Error handling
thiserror = "1.0"
anyhow = "1.0"

# Numerical computations
ndarray = "0.15"
statrs = "0.16"  # Statistical computations
black_scholes = "0.5"  # Options pricing

# Utilities
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde"] }
futures = "0.3"

# Visualization (optional)
plotters = "0.3"
colorous = "1.0.10"
reqwest = { version = "0.11", features = ["json", "rustls-tls"] }
