[package]
name = "viz_native"
version = "0.1.0"
edition = "2021"

[dependencies]
options_core = { path = "../options_core", features = ["native"] }
eframe = "0.27"
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
