[package]
name = "viz_web"
edition = "2021"
version = "0.1.0"

[dependencies]
leptos = { version = "0.6", features = ["csr"] }
wasm-bindgen = "0.2"
gloo = { version = "0.11", features = ["timers"] }
options_core = { path = "../options_core", default-features = false, features = ["wasm"] }
